"""The published diagrams still match the sources they were drawn from.

A unit test rather than a `make lint` stage on purpose: a new lint stage has to
be registered in the quality witness (tests/test_quality_witness.py enforces
that), which would move the witness total for a reason that has nothing to do
with witnesses. This runs in the same pytest job and fails in milliseconds.
"""

from __future__ import annotations

import pathlib

import pytest

from scripts import build_diagrams as bd


def test_there_is_at_least_one_authored_diagram():
    """Otherwise every assertion below is vacuously true."""
    assert bd.sources(), "no authored diagram in docs/img/src"


@pytest.mark.parametrize("theme", sorted(bd.PALETTES))
def test_every_generated_file_matches_its_source(theme):
    for source in bd.sources():
        target = bd.OUT / f"{source.stem}-{theme}.svg"
        assert target.exists(), f"{target.name} was never generated"
        assert target.read_text() == bd.render(source.read_text(), theme), (
            f"{target.name} is stale — run `python -m scripts.build_diagrams`"
        )


def test_the_two_themes_actually_differ():
    """A generator that emitted one palette twice would pass everything above
    and leave dark readers with white boxes."""
    source = bd.sources()[0].read_text()
    assert bd.render(source, "light") != bd.render(source, "dark")


def test_a_source_without_a_palette_marker_is_refused():
    """Silently emitting an unthemed copy is the failure worth catching: it
    renders correctly for whoever authored it and wrong for everyone else."""
    with pytest.raises(SystemExit):
        bd.render("<svg><style>.bx{fill:#fff}</style></svg>", "light")


def test_no_generated_file_is_orphaned():
    """A renamed source leaves its old outputs behind, still referenced by the
    Markdown and no longer regenerated by anything."""
    expected = {f"{s.stem}-{t}.svg" for s in bd.sources() for t in bd.PALETTES}
    published = {p.name for p in bd.OUT.glob("*.svg")}
    assert published == expected, f"orphaned: {sorted(published - expected)}"


def test_every_published_diagram_is_referenced_by_a_doc():
    """A diagram nobody links to is a diagram nobody sees."""
    docs = "\n".join(p.read_text() for p in pathlib.Path(bd.ROOT / "docs").glob("*.md"))
    for source in bd.sources():
        assert f"{source.stem}-light.svg" in docs, f"{source.stem} is published but unreferenced"
