"""Turn a promoted query template into a published Power BI dashboard.

See docs/00-plan.md §18. The input is a candidate the promoter released —
a literal-free SQL template, its measures and dimensions, and a title derived
from the catalog. The output is a SemanticModel and a Report in Fabric, with
lineage recorded in OpenMetadata, published under the identity of the person
who asked for it.

Nothing here is generated by a model. The definitions are deterministic
functions of the template and the catalog, because a dashboard that says
something different on Tuesday is not a dashboard anyone can rely on.
"""
