#!/usr/bin/env python3
"""The sidebar and `docs/` must agree, judged on what is COMMITTED.

Starlight fails the build on a sidebar slug with no page, so an entry added
without its document takes the whole docs site down -- and it does so only in
CI, because the author's working tree has the file. That is the failure this
guards: `git ls-files`, not the filesystem, decides what exists.

The reverse direction is a lesser fault with the same cause: a document nobody
can navigate to is one nobody reads.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "website" / "astro.config.ts"
# `index` is generated by website/scripts/sync-docs.ts, not carried in docs/.
GENERATED = {"index"}


def sidebar_slugs(text: str) -> list[str]:
    return re.findall(r"\{\s*slug:\s*'([^']+)'\s*\}", text)


def tracked_docs() -> set[str]:
    out = subprocess.run(
        ["git", "ls-files", "docs"], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.split()
    # Every depth: a slug is the path under docs/ without its suffix, so a
    # nested page like `adr/0001-two-executors` is named exactly as the
    # sidebar names it. Filtering to top level here is what made the first
    # version of this script accuse a committed ADR of being missing.
    return {p[len("docs/") : -len(".md")] for p in out if p.endswith(".md")}


def main() -> int:
    slugs = sidebar_slugs(CONFIG.read_text())
    if not slugs:
        print(f"no sidebar slugs found in {CONFIG.relative_to(ROOT)} -- has its shape changed?")
        return 1
    docs = tracked_docs()

    orphans = [s for s in slugs if s not in docs and s not in GENERATED]
    unreachable = sorted(d for d in docs if d not in slugs)
    duplicates = sorted({s for s in slugs if slugs.count(s) > 1})

    for slug in orphans:
        local = (ROOT / "docs" / f"{slug}.md").exists()
        why = "exists locally but is NOT COMMITTED" if local else "does not exist"
        print(f"sidebar names '{slug}': docs/{slug}.md {why}")
    for slug in unreachable:
        print(f"docs/{slug}.md is committed but no sidebar entry reaches it")
    for slug in duplicates:
        print(f"sidebar names '{slug}' more than once")

    if orphans or unreachable or duplicates:
        print(f"\n{len(slugs)} sidebar entries, {len(docs)} committed docs -- they disagree.")
        return 1
    print(f"sidebar and docs/ agree: {len(docs)} pages, all reachable, all committed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
